# vim:fileencoding=utf-8:foldmethod=marker

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

# --- CZCIONKA ---
# Używamy pełnej nazwy wykrytej przez fc-list
font_family      MesloLGS Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        14.0

# --- WYDAJNOŚĆ ---
repaint_delay    10
input_delay      3
sync_to_monitor  no

# --- WYGLĄD OKNA ---
window_padding_width 15
background_opacity   0.85
hide_window_decorations no
confirm_os_window_close 0
initial_window_width 100c
initial_window_height 30c
remember_window_size yes
remember_window_position yes

# --- UKŁADY OKIEN (SPLITS) ---
# To pozwala na ręczne dzielenie okna (pion/poziom)
enabled_layouts splits,stack

# --- SKRÓTY KLAWISZOWE DLA SPLITÓW ---
# Otwiera nowy panel w tym samym folderze (--cwd=current)
map ctrl+shift+enter launch --location=vsplit --cwd=current
map ctrl+shift+backspace launch --location=hsplit --cwd=current

# Nawigacja między panelami (H,J,K,L jak w Vimie)
map ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right
map ctrl+shift+k neighboring_window up
map ctrl+shift+j neighboring_window down

# Pełny ekran dla jednego panelu (Toggle Zoom)
map ctrl+shift+f toggle_layout stack

# Zamykanie aktywnego panelu
map ctrl+shift+w close_window

# Wyszukiwanie                                                                                                                                                                                                 
# map ctrl+f search_scrollback                                                                                                                                                                                 
# Open scrollback history in fzf in new window                                                                                                                                                                 
map ctrl+f launch --type=overlay --stdin-source=@screen_scrollback /usr/bin/fzf --ignore-case --no-sort --bind "enter:execute-silent(echo -n {} | wl-copy)+abort,ctrl-y:execute-silent(echo -n {} | wl-copy)"

# --- ZACHOWANIE ---
shell .
editor vim
enable_audio_bell no

# Clipboard
copy_on_select yes

# Tabs
tab_bar_edge top
tab_bar_style powerline

# Mouse
mouse_hide_wait 3.0

# Scrollback
scrollback_lines 10000

# --- USTAWIENIA KURSORA ---
cursor_shape beam
cursor_beam_thickness 1.5
cursor_blink_interval 0
#cursor #f5e0dc
#cursor_text_color #11111b

# --- KOLORY (Catppuccin Mocha) ---
# Lepiej uzyc komendy: 'kitten themes'
#
#background            #1e1e2e
#foreground            #cdd6f4
#selection_background  #585b70
#selection_foreground  #cdd6f4
#url_color             #f5e0dc

# Kolory ANSI
#color0 #45475a
#color8 #585b70
#color1 #f38ba8
#color9 #f38ba8
#color2 #a6e3a1
#color10 #a6e3a1
#color3 #f9e2af
#color11 #f9e2af
#color4 #89b4fa
#color12 #89b4fa
#color5 #f5c2e7
#color13 #f5c2e7
#color6 #94e2d5
#color14 #94e2d5
#color7 #bac2de
#color15 #a6adc8

